services:
  web-app:
    image: ghcr.io/${GITHUB_REPOSITORY}/web-app:${IMAGE_TAG:-latest}
    container_name: automatch-web-prod
    ports:
      - "3000:3000"
    restart: always
    networks:
      - automatch-net-prod

networks:
  automatch-net-prod:
    external: true
