name: CD - Frontend Production

on:
  push:
    branches:
      - main

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Web App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=http://187.124.128.145:8080/api/v1
          tags: |
            ghcr.io/${{ github.repository }}/web-app:latest
            ghcr.io/${{ github.repository }}/web-app:${{ github.sha }}

      - name: Prepare VPS Directories and Copy docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mkdir -p automatch-frontend/prod
            cat << 'EOF' > automatch-frontend/prod/docker-compose.frontend.yml
            services:
              web-app:
                image: ghcr.io/${GITHUB_REPOSITORY}/web-app:${IMAGE_TAG:-latest}
                container_name: automatch-web-prod
                ports:
                  - "3000:3000"
                restart: always
                networks:
                  - automatch-net-prod

            networks:
              automatch-net-prod:
                external: true
            EOF

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd automatch-frontend/prod
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
            docker compose -p automatch-web-prod -f docker-compose.frontend.yml pull
            docker compose -p automatch-web-prod -f docker-compose.frontend.yml up -d
            docker system prune -af
